# Generated by Django 5.2.1 on 2025-05-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-show__title'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='representation',
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogue.show', verbose_name='Films'),
            preserve_default=False,
        ),
    ]
