# Generated by Django 5.2.1 on 2025-05-21 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_review_options_remove_review_representation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='types',
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_types', to='catalogue.artist', verbose_name='Artiste')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_types', to='catalogue.type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Association artiste/type',
                'verbose_name_plural': 'Associations artiste/type',
                'db_table': 'artist_types',
                'unique_together': {('artist', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='catalogue.artisttype', verbose_name='Artiste + Type')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_type_links', to='catalogue.show', verbose_name='Spectacle')),
            ],
            options={
                'verbose_name': 'Participation artistique',
                'verbose_name_plural': 'Participations artistiques',
                'db_table': 'artist_type_show',
                'unique_together': {('artist_type', 'show')},
            },
        ),
    ]
